# Site settings
title: Zyzle's blog
email: n1l0c2501@gmail.com
description: "Personal blog"
baseurl: ""
url: "http://zyzle.github.io"
twitter_username: zyzle2501
github_username:  zyzle

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: pretty
